import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-dark min-h-screen  ${geistSans.variable} ${geistMono.variable}`}
      >
        <div className="flex">
          {/* Sidebar */}
          <Sidebar />

          {/* Right content */}
          <div className="flex flex-col flex-1 min-w-0">
            <Header />

            <main className="flex-1 overflow-y-auto px-6 py-4">
              <div className="w-full">
                {children}
              </div>
            </main>
          </div>
        </div>

      </body>
    </html >

  );
}
